/*
#	Le livre de Java 1er langage
#	A. Tasso
#	Chapitre 12 : Créer une interface graphique
#	Section  :  Une première application avec NetBeans
#	Fichier  :  CercleSwing.java
#	Class    :  CercleSwing
*/

// Le fichier CercleSwing.java se trouve dans le répertoire 
// Sources/Exemples/Chapitre12/NetBeansProjects/PremierProjet/src/Introduction
package Introduction;


// La classe CercleSwing hérite des propriétés et méthodes de la la classe JFRame
public class CercleSwing extends javax.swing.JFrame {

    /** Creates new form CercleSwing */
    public CercleSwing() {
        // Afficher les composants graphiques tels qu'ils sont placés dans le fenêtre Design
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rayonLabel = new javax.swing.JLabel();
        perimetreLabel = new javax.swing.JLabel();
        resultatLabel = new javax.swing.JLabel();
        calculerBtn = new javax.swing.JButton();
        saisieRayon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculer le périmètre d'un cercle");

        rayonLabel.setText("Rayon :");

        perimetreLabel.setText("Périmètre : ");

        resultatLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultatLabel.setText("0");

        calculerBtn.setText("Calculer");
        calculerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculerBtnActionPerformed(evt);
            }
        });

        saisieRayon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        saisieRayon.setText("0");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(rayonLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(saisieRayon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(55, 55, 55)
                .add(perimetreLabel)
                .add(27, 27, 27)
                .add(resultatLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .add(calculerBtn)
                .add(163, 163, 163))
        );

        layout.linkSize(new java.awt.Component[] {perimetreLabel, rayonLabel, resultatLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rayonLabel)
                    .add(perimetreLabel)
                    .add(resultatLabel)
                    .add(saisieRayon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(calculerBtn)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Les instructions placées au sein de la fonction calculerBtnActionPerformed()
// ne sont exécutées que lorsque l'utilisateur clique sur le bouton Calculer.
private void calculerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculerBtnActionPerformed
// Récuperer la valeur du rayon saisi dans le champs de saisie saisieRayon
double rayon = Double.parseDouble(saisieRayon.getText());//GEN-LAST:event_calculerBtnActionPerformed
// Calculer le périmètre du cerecle
double perimetre = 2* Math.PI* rayon;
// Afficher le périmètre dans le champ de texte resultatLabel
resultatLabel.setText(Double.toString(perimetre));
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
      java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           new CercleSwing().setVisible(true);
       } 
      }) ;
    }
    // Les variables ci-après sont créées en même temps que les objets placés dans la fenêtre Design
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculerBtn;
    private javax.swing.JLabel perimetreLabel;
    private javax.swing.JLabel rayonLabel;
    private javax.swing.JLabel resultatLabel;
    private javax.swing.JTextField saisieRayon;
    // End of variables declaration//GEN-END:variables
 
}
