/*
#	Le livre de Java 1er langage
#	A. Tasso
#	Chapitre 12 : Créer une interface graphique
#	Section  : Projet
#	Fichier  : LigneEdit.java
#	Class    : LigneEdit
*/

// Le fichier LigneEdit.java se trouve dans le répertoire 
// Sources/Projet/Chapitre12/NetBeansProjects/ProjetChapitre12/src/Projet

package Projet;

public class LigneEdit extends javax.swing.JPanel {
    public LigneEdit(LigneComptable tmp) {
        initComponents();
        setBounds(0, 0,200, 70);
        setVisible(true);
        // Afficher le motif de la transaction dans le composant nommé labelMotif
        labelMotif.setText(tmp.getMotif());
        // Afficher le motif de la transaction dans le composant nommé labelTransaction
        labelTransaction.setText(tmp.getMode());
        // Afficher le montant de la transaction dans le composant nommé labelValeur
        labelValeur.setText(Double.toString(tmp.getValeur()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMotif = new javax.swing.JLabel();
        labelTransaction = new javax.swing.JLabel();
        labelValeur = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 240));
        setLayout(new java.awt.GridLayout(1, 3));

        labelMotif.setText("Motif : ");
        add(labelMotif);

        labelTransaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTransaction.setText("Transaction :");
        add(labelTransaction);

        labelValeur.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelValeur.setText("Valeur :");
        add(labelValeur);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelMotif;
    private javax.swing.JLabel labelTransaction;
    private javax.swing.JLabel labelValeur;
    // End of variables declaration//GEN-END:variables

}
